In [1]:
import torch


In [2]:
adj = torch.tensor([[0,1,1,0,1],[1, 0, 1, 0, 0],[1,1,0, 1,1],[0,0,1,0,1],[1,0,1,1,0]])

In [6]:
adj[4]

tensor([1, 0, 1, 1, 0])

In [4]:
(adj > 0).float().numpy().astype(int)

array([[0, 1, 1, 0, 1],
       [1, 0, 1, 0, 0],
       [1, 1, 0, 1, 1],
       [0, 0, 1, 0, 1],
       [1, 0, 1, 1, 0]])

In [32]:
n=4

m=64
a = torch.normal((n,m))
c = a.view(1, n, m) - a.view(n, 1, m)
-(c*c).sum(axis=2)

TypeError: normal(): argument 'mean' (position 1) must be Tensor, not tuple

In [6]:
n=5
m=3

In [16]:
u = torch.normal(mean=torch.zeros((n, m)), std=torch.ones((n, m))*0.7)
#e=torch.clamp(e, min=0, max=1)
print(u)

tensor([[-1.5149, -0.8233,  1.1595],
        [ 0.7311,  0.9124, -0.4467],
        [ 0.0130, -1.0934, -0.3047],
        [ 0.0624, -0.4462,  0.7783],
        [-0.9767,  0.5908,  1.0116]])


In [20]:
u = torch.normal(mean=torch.zeros((n, n)), std=torch.ones((n, n))*0.7)

In [21]:
u

tensor([[ 0.6687,  0.4437,  0.7894, -0.2134,  0.6370],
        [ 0.1483, -0.0610, -1.0466, -0.1374,  1.5158],
        [ 0.2764,  1.3181,  0.1103,  0.0495,  0.1683],
        [-1.1976, -1.3733, -1.2291,  0.1554, -0.2879],
        [-0.5835,  1.2205,  0.2042,  0.1849,  0.3115]])

In [25]:
edge_index = torch.tensor([[0,0,0,1,1,3],[2,3,4,3,4,4]])
num_nodes = 5

In [28]:
torch.concat([edge_index[0]*num_nodes + edge_index[1], edge_index[1]*num_nodes + edge_index[0]])

tensor([ 2,  3,  4,  8,  9, 19, 10, 15, 20, 16, 21, 23])

In [13]:

a.view(2,1,3)

tensor([[[1, 2, 3]],

        [[4, 5, 6]]])

In [2]:
import torch_geometric

In [3]:
from torch_geometric.datasets import Planetoid
import torch_geometric.transforms as T

In [9]:
dataset = Planetoid(root='/tmp/'+str('Cora'), name='Cora',transform=T.NormalizeFeatures())[0]

In [10]:
dataset.y

tensor([3, 4, 4,  ..., 3, 3, 3])

In [5]:
with open('cora_attrs.txt', 'a') as f:
    for i in dataset.x.numpy():
        for j in i[:len(i)-1]:
            f.write(str(j)+',')
        f.write(str(i[len(i)-1])+'\n')

In [6]:
with open('cora_edges.txt', 'a') as f:
    for i in (dataset.edge_index.T.tolist()):
        f.write(str(i[0])+','+str(i[1])+'\n')

In [8]:
with open('cora_labels.txt', 'a') as f:
    for i in (dataset.y.tolist()):
        f.write(str(i)+'\n')